//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataModelLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Doctor
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Doctor()
        {
            this.DiseaseRegistrations = new HashSet<DiseaseRegistration>();
            this.Prescribes = new HashSet<Prescribe>();
        }
    
        public int DoctorID { get; set; }
        public string DoctorUserName { get; set; }
        public string DoctorName { get; set; }
        public string DoctorFamily { get; set; }
        public string DoctorPassword { get; set; }
        public Nullable<System.DateTime> DoctorStartDate { get; set; }
        public Nullable<System.DateTime> DoctorEndDate { get; set; }
        public string DoctorSpecialty { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DiseaseRegistration> DiseaseRegistrations { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Prescribe> Prescribes { get; set; }
    }
}
