//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataModelLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class TurnRating
    {
        public int TurnRatingsid { get; set; }
        public int PatientID { get; set; }
        public int DoctorID { get; set; }
        public Nullable<System.DateTime> TurnRatingDate { get; set; }
        public bool Acctive { get; set; }
    
        public virtual Doctor Doctor { get; set; }
        public virtual Patient Patient { get; set; }
    }
}
