//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataModelLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Vw_Patients
    {
        public string PatientName { get; set; }
        public string PatientFamily { get; set; }
        public Nullable<System.DateTime> PatientDateBirth { get; set; }
        public string PatientAddress { get; set; }
        public string PatientPhoneNumber { get; set; }
        public byte PatientGender { get; set; }
        public int PatientID { get; set; }
        public string Gender { get; set; }
    }
}
