//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataModelLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Vw_prescibes
    {
        public string PatientName { get; set; }
        public string PatientFamily { get; set; }
        public string MedicineName { get; set; }
        public int MedicineCount { get; set; }
        public Nullable<System.DateTime> PrescribeDate { get; set; }
        public string Gender { get; set; }
        public string DoctorFamily { get; set; }
        public string DoctorName { get; set; }
        public long MedicineSaleePrice { get; set; }
    }
}
