//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataModelLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Vw_TurnRatings
    {
        public bool Acctive { get; set; }
        public Nullable<System.DateTime> TurnRatingDate { get; set; }
        public int DoctorID { get; set; }
        public int PatientID { get; set; }
        public string PatientName { get; set; }
        public string PatientFamily { get; set; }
        public string DoctorName { get; set; }
        public string DoctorFamily { get; set; }
    }
}
